### ISSUE TITLE
Can't run Xcos simulation with Modelica blocks

### ISSUE THREAD

**Issue by N0rbert** [flathub/org.scilab.Scilab#2]
Steps to reproduce:
1. Install Scilab using flatpak
 
       flatpak install flathub org.scilab.Scilab

1. Launch Scilab from flatpak

       flatpak run org.scilab.Scilab

1. In the menubar click ? → Scilab Demonstrations, then select Xcos → Electrical Systems → RLC Circuit, start simulation by Simulation → Start

Expected results:

* Scilab compiled modelica model, then simulation started 

Actual results:

* Scilab can't compile model, shows the following in the Console:

```
--------------------------------------------\
 Main Modelica : /tmp/SCI_TMP_34_oMqemM/RLC_Modelica_im.mo

 Flat Modelica : /tmp/SCI_TMP_34_oMqemM/RLC_Modelica_imf.mo
 Simulation C code :/tmp/SCI_TMP_34_oMqemM/RLC_Modelica_im.c
   Generate a loader file
   Generate a Makefile
   ilib_gen_Make: Copy compilation files (Makefile*, libtool...) to TMPDIR
   ilib_gen_Make: Copy RLC_Modelica_im.c to TMPDIR
   ilib_gen_Make: configure : Generate Makefile.
Detection of C/C++/Fortran Compilers 
checking for a BSD-compatible install... /usr/bin/install -c 
checking whether build environment is sane... yes 
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p 
checking for gawk... gawk 
checking whether make sets $(MAKE)... yes 
checking whether make supports nested variables... yes 
checking whether to enable maintainer-specific portions of Makefiles... no 
checking build system type... x86_64-unknown-linux-gnu 
checking host system type... x86_64-unknown-linux-gnu 
checking how to print strings... printf 
checking whether make supports the include directive... yes (GNU style) 
checking for gcc... no 
checking for cc... no 
checking for cl.exe... no 

  "sorry compiling problem"                                                
  "ilib_gen_Make: An error occurred during the detection of the compiler(s). Set ilib_verbose(2) for more information."

  "c_pass1: build the modelica meta-block failed"

  "xcos_simulate: Error during block parameters update."
```

Additional info - Ubuntu 18.04.5 LTS, Scilab 6.1.1 using [official 6.1.1 binary distribution](https://www.scilab.org/download/6.1.1/scilab-6.1.1.bin.linux-x86_64.tar.gz) works normally here.

**Comment by kevinsmia1939** [comment]
Hi,
Thanks for the report. It should be fix in this pr. https://github.com/flathub/org.scilab.Scilab/pull/3
Uninstall the current scilab flatpak and install the new one in the above pr. Let me know if it work.

**Comment by N0rbert** [comment]
Thanks for quick rebuild. 
Updated version [from pr](https://github.com/flathub/org.scilab.Scilab/pull/3#issuecomment-894516232) works as expected.
