### ISSUE TITLE
Two bugs in Flatpak Scilab. 

### ISSUE THREAD

**Issue by MInessota** [flathub/org.scilab.Scilab#4]
SciLab 6.1.1 Flatpak - Linux Mint 20.2

- Flatpak uses the wrong icon, instead of using the Scilab icon, it is using the Scinotes icon.

- GTK error message: " Failed to load module "xapp-gtk3-module". 

![scilab-flatpack](https://user-images.githubusercontent.com/28904791/128638761-07e93881-b9df-4172-949d-dcfaeaffc8ca.png)

**Comment by kevinsmia1939** [comment]
The GTK error message: " Failed to load module "xapp-gtk3-module" is known Flatpak issue, but harmless.
This icon should be fix now, try update it in a few hours.

**Comment by kevinsmia1939** [comment]
Also, have you update Flatpak to the latest version on Linux Mint? Linux Mint ship older version of Flatpak by default.
