### ISSUE TITLE
update to 2024.0.0

### ISSUE THREAD

**Issue by CC-Hsu** [flathub/org.scilab.Scilab#55]
Hi, Team,

There is a new update available.

https://www.scilab.org/download/scilab-2024.0.0

Hope this can be packaged.

Best regards.

**Comment by kevinsmia1939** [comment]
scilab is already on latest version, the metainfo just need to display correct version.

**Comment by kevinsmia1939** [comment]
I updated Scilab and its metadata, I will close this.
